### ISSUE TITLE
Remove JCommander based command line argument handling

### ISSUE THREAD

**Issue by svenreimers** [JUGBodensee/TweetwallFX#69]
Reason:
Deployment using commandline args is not very nice, if you which resources will make up one special deployment e.g. JavaOne, Devoxx...
A better fit may be some kind of configuration in the build.gradle or in resources which is read by the application so that just java -jar .. is enough for running the app

**Comment by mklaehn** [comment]
was fixed with https://github.com/JUGBodensee/TweetwallFX/commit/58f59a6aa8cbf4b8edaa25e6bf07c301dfb52df6
